package hulkstore_.view.login;

import hulkstore_.controller.login.CLogin;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.log4j.Logger;

/**
 * Main view of the User Login
 * 
 * @author Luis Mercado
 * @version 0.1
 * @since 2020-03-11
 */
public class UILogin extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(UILogin.class.getName());
    private final CLogin controller;
    
    /**
     * Constructor.
     * 
     * @param controller 
     */
    public UILogin(CLogin controller) {        
        initComponents();
        this.setVisible(true);
        this.setTitle("LOGIN - HulkStore");
        setLocationRelativeTo(null);        
        this.controller = controller;
        LOG.info("view UILogin loaded");        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniSettings = new javax.swing.JMenuItem();
        mniClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/hulkstore_/resources/images/login_icon.png")).getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkstore_/resources/images/login_img.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        txtUser.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 25));

        pwdPass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        getContentPane().add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 25));

        btnLogin.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnLogin.setText("Ingresar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        btnExit.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnExit.setText("Salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jMenuBar1.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        mniSettings.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        mniSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkstore_/resources/images/settings_icon.png"))); // NOI18N
        mniSettings.setText("Configuración");
        mniSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSettingsActionPerformed(evt);
            }
        });
        jMenu1.add(mniSettings);

        mniClose.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        mniClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkstore_/resources/images/exit_icon.png"))); // NOI18N
        mniClose.setText("Cerrar");
        mniClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mniClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenu2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N

        mniAbout.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        mniAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hulkstore_/resources/images/about_icon.png"))); // NOI18N
        mniAbout.setText("Acerca De...");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        jMenu2.add(mniAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        controller.validate(this.txtUser, this.pwdPass);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        controller.close();
    }//GEN-LAST:event_btnExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.close();
    }//GEN-LAST:event_formWindowClosing

    private void mniCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCloseActionPerformed
        controller.close();
    }//GEN-LAST:event_mniCloseActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        String imagePath = "/hulkstore_/resources/images/login_icon.png";
        LOG.debug("Loading image = " + imagePath);
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));        
        LOG.info("Show information pop-up window");
        JOptionPane.showMessageDialog(null, "Inventarios\nHulkStore - 2020\nTodo1", "Acerca de...", JOptionPane.INFORMATION_MESSAGE, icon);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSettingsActionPerformed
        controller.setting();
    }//GEN-LAST:event_mniSettingsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JMenuItem mniSettings;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
